name: Build game
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  webgl:
    name: Build WebGL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-BWJamEight-WebGL
      - name: Build
        id: build
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          customImage: 'unityci/editor:2020.3.32f1-webgl-1'
      - name: Push artifact
        id: push
        uses: actions/upload-artifact@v2
        with:
          name: Build-WebGL
          path: build
  windows:
    name: Build Windows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-BWJamEight-Windows
      - name: Build
        id: build
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          customImage: 'unityci/editor:windows-2020.3.32f1-universal-windows-platform-1.0.0'
      - name: Push artifact
        id: push
        uses: actions/upload-artifact@v2
        with:
          name: Build-Windows
          path: build
  mac:
    name: Build Mac
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-BWJamEight-Mac
      - name: Build
        id: build
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneOSX
          customImage: 'unityci/editor:2020.3.32f1-mac-mono-1'
      - name: Push artifact
        id: push
        uses: actions/upload-artifact@v2
        with:
          name: Build-Mac
          path: build
