# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch: {}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: echo run id
        run: echo ${{ github.run_id }}
      - name: echo run number
        run: echo ${{ github.run_number }}
      - name: echo run attempt
        run: echo ${{ github.run_attempt }}
